name: "Wanderer Deployer"
author: "Roman Zipp"
branding:
  icon: "download-cloud"
  color: "red"
description: "Deploy builds to your Nomad Cluster via Wanderer"

inputs:
  endpoint:
    description: "The base url to your Wanderer instance"
    required: true
  token:
    description: "The specified Wanderer authentication API token"
    required: true
  server:
    description: "The server ID from Wanderer"
    required: true
  job:
    description: "The Nomad job ID"
    required: true
  selector:
    description: "The version selector as specified in Wanderer UI"
    required: true
  version:
    description: "The new version to be deployed"
    required: true
  cf_access_client_id:
    description: "Cloudflare Access Client Id"
    required: false
  cf_access_client_secret:
    description: "Cloudflare Access Client Secret"
    required: false

runs:
  using: "composite"
  steps:
    - run: chmod +x $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        ENDPOINT: ${{ inputs.endpoint }}
        TOKEN: ${{ inputs.token }}
        SERVER: ${{ inputs.server }}
        JOB: ${{ inputs.job }}
        SELECTOR: ${{ inputs.selector }}
        VERSION: ${{ inputs.version }}
        CF_ACCESS_CLIENT_ID: ${{ inputs.cf_access_client_id }}
        CF_ACCESS_CLIENT_SECRET: ${{ inputs.cf_access_client_secret }}
